name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Firebase Config
        run: |
          printf 'var firebaseConfig = {\n  apiKey: "%s",\n  authDomain: "%s",\n  projectId: "%s",\n  storageBucket: "%s.appspot.com",\n  messagingSenderId: "235936270485",\n  appId: "%s"\n};' \
          "${{ secrets.FIREBASE_API_KEY }}" \
          "${{ secrets.FIREBASE_AUTH_DOMAIN }}" \
          "${{ secrets.FIREBASE_PROJECT_ID }}" \
          "${{ secrets.FIREBASE_PROJECT_ID }}" \
          "${{ secrets.FIREBASE_APP_ID }}" > firebase-config.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages
