name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Firebase Config
        run: |
          cat <<EOF > firebase-config.js
          var firebaseConfig = {
          apiKey: "${{ secrets.FIREBASE_API_KEY }}",
          authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
          storageBucket: "${{ secrets.FIREBASE_PROJECT_ID }}.appspot.com",
          messagingSenderId: "235936270485",
          appId: "${{ secrets.FIREBASE_APP_ID }}"
          };
          EOF

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages
